### ISSUE TITLE
运行脚本出现 这个问题 / This problem occurs when running the script

### ISSUE THREAD

**Issue by ylmcr7** [boukeversteegh/pptpd-monitor#11]
[root@ylm_aliyun src]# ./pptd-monitor.py
Traceback (most recent call last):
  File "./pptd-monitor.py", line 288, in <module>
    logfile = args.file.file
AttributeError: '_io.TextIOWrapper' object has no attribute 'file'

**Comment by boukeversteegh** [comment]
有可能你的系统没有【/var/log/syslog】。请试一下加文件参数【-f】。例 `./pptpd-monitor.py -f /etc/pttp/pttd.log` 要看你境况

**Comment by ylmcr7** [comment]
还是不行  
[root@ylm_aliyun ppp]# ls /var/log/syslog
/var/log/syslog
[root@ylm_aliyun ppp]# ./pptpd-monitor.py -f /var/log/syslog
Traceback (most recent call last):
  File "./pptpd-monitor.py", line 288, in <module>
    logfile = args.file.file
AttributeError: '_io.TextIOWrapper' object has no attribute 'file'

**Comment by boukeversteegh** [comment]
Fixed by https://github.com/boukeversteegh/pptpd-monitor/commit/0d1c1d48b49b2008e16ef4a9bbca45b0753f1162
