### ISSUE TITLE
usernames with symbol "-" aren't displayed correctly

### ISSUE THREAD

**Issue by Negossia** [boukeversteegh/pptpd-monitor#5]
Hello!
i use your script, and my usernames which contains symbol "-" (user-1, user-2, etc) displayed like "None", and i cant see their statistic with "--rotate" parameter.

**Comment by boukeversteegh** [comment]
Hi @Negossia, please `git checkout bug/username-regex` to see if the problem is solved

**Comment by Negossia** [comment]
thansk for resolving this problem!
very good program!
i see usernames normally now.

**Comment by boukeversteegh** [comment]
Thank you for testing, merged with master in 3c6b5435396ed44b8beb78213faa02fbe2b7820b
